In [24]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KDTree
import os
import pickle

In [11]:
data_path = 'track_master_df.csv'
train_df = pd.read_csv(data_path)
test_df = pd.read_csv('test_case.csv')

drop_cols = ['artist', 'album', 'track', 'track_id']

X_train = train_df.drop(columns = drop_cols)
X_test = test_df.drop(columns = drop_cols)

In [12]:
train_df.head()

artist                 album                       track  \
0       Lorde          Pure Heroine                        Ribs   
1      Clairo              Immunity                        Bags   
2  The Script            The Script  The Man Who Can't Be Moved   
3       Adele                    21         Rolling in the Deep   
4  Bruno Mars  Doo-Wops & Hooligans                     Grenade   

                 track_id  danceability  energy  key  loudness  mode  \
0  2MvvoeRt8NcOXWESkxWn3g         0.511   0.472    4    -9.277     1   
1  6UFivO2zqqPFPoQYsEMuCc         0.742   0.546    1    -7.694     1   
2  4Musyaro0NM5Awx8b5c627         0.609   0.629   10    -5.024     1   
3  1eq1wUnLVLg4pdEfx9kajC         0.730   0.770    8    -5.114     1   
4  4lLtanYk6tkMvooU0tWzG8         0.706   0.558    2    -7.237     0   

   speechiness  acousticness  instrumentalness  liveness  valence    tempo  \
0       0.0910         0.534             0.614    0.1100   0.0399  127.978   
1       0.0315         0.172             0.380    0.1150   0.8680  104.996   
2       0.0264         0.425             0.000    0.0978   0.3250   99.955   
3       0.0298         0.138             0.000    0.0473   0.5070  104.948   
4       0.0593         0.146             0.000    0.1180   0.2270  110.443   

   duration_ms  time_signature  
0       258969               4  
1       260520               4  
2       241467               4  
3       228093               4  
4       223253               4

In [13]:
test_df.head()

artist                                   album  \
0           Boys Like Girls                         Boys Like Girls   
1  The All-American Rejects                              Move Along   
2          The Spill Canvas  No Really, I'm Fine (Standard Version)   
3               Simple Plan             Get Your Heart On! (Deluxe)   
4              Fall Out Boy                From Under The Cork Tree   

                    track                track_id  danceability  energy  key  \
0          Hero / Heroine  1AnesEZjtNHT7Nr2Y4BuNR         0.422   0.904    0   
1     Dirty Little Secret  5ZdzNVOmCSp5HFLk0EgvJS         0.469   0.955   10   
2            All over You  4b9jRNwMUvABxTD1amyfA6         0.554   0.941   10   
3        You Suck At Love  2khCn0FtcHpiOPRchJxjfs         0.517   0.961    2   
4  Sugar, We're Goin Down  2TfSHkHiFO4gRztVIkggkE         0.494   0.841    7   

   loudness  mode  speechiness  acousticness  instrumentalness  liveness  \
0    -4.531     1       0.1020      0.020000          0.000004     0.686   
1    -4.253     1       0.0432      0.000343          0.000001     0.548   
2    -3.159     0       0.0347      0.008480          0.000000     0.102   
3    -2.482     1       0.0494      0.002450          0.000000     0.173   
4    -4.784     1       0.0838      0.005790          0.000000     0.122   

   valence    tempo  duration_ms  time_signature  
0    0.320  163.929       232240               4  
1    0.462  143.853       193653               4  
2    0.524  134.916       202432               4  
3    0.741  155.976       191040               4  
4    0.567  162.013       229093               4

In [113]:
tree = KDTree(X_train, leaf_size=1)
s = pickle.dumps(tree)
tree_copy = pickle.loads(s)       
dist, ind = tree_copy.query(X_test, k=10)   

In [119]:
with open('kdtree_model_1.pkl', 'wb') as f:
    pickle.dump(tree, f)

In [114]:
print(ind)
print(dist)

[[5796 8358 8207 5129 6158  617 1975 9777 8789 6532]
 [8968 3596 2927 6490 6663 2567 7983 6125 7336 9073]
 [9176 4882 4101 8276 8796 5515  754 2082 2222 2006]
 [4987 4126 1821 3629 9717 6842 7836 3207 3864 6061]
 [ 282 9362 3777 6976 1893 2512  994 9290 5768 4901]
 [8969 1555 6383 9810 7391 1550 7501 4045 2857  838]
 [1021 2670 3100 3725 2413 3271 9531 7675 3923 6840]
 [1768 7504 6386 5489 5914 7500 1741 7802 7636 2105]
 [4893 4348 1956 6813 4368 2581 8874 4289 2290 7212]
 [1824 4251 1044 6981 7148 7784 3366 4662 5850 5386]
 [3325 4117 7688  875 5520 4450 1186 1779 4274 1773]
 [5567 8292 8676 4080 6379 3331 4518 7765 1992 6850]
 [9541 5685  413 4029 9781 2205 2651 3007  149 5672]]
[[3.95792277e+01 4.55104096e+01 4.66148209e+01 5.04586530e+01
  5.23685143e+01 6.74501350e+01 6.88299566e+01 7.09134548e+01
  7.42706218e+01 7.79311667e+01]
 [2.84217094e-14 2.25508120e+01 4.31963084e+01 4.53231033e+01
  4.56576244e+01 4.85083484e+01 6.80127747e+01 6.94868939e+01
  7.22747768e+01 7.22747768e+

In [118]:
test_df.head(50)

artist                                   album  \
0              Boys Like Girls                         Boys Like Girls   
1     The All-American Rejects                              Move Along   
2             The Spill Canvas  No Really, I'm Fine (Standard Version)   
3                  Simple Plan             Get Your Heart On! (Deluxe)   
4                 Fall Out Boy                From Under The Cork Tree   
5     The All-American Rejects                              Move Along   
6                   Yellowcard                            Ocean Avenue   
7                 All Time Low                    So Wrong, It's Right   
8   The Red Jumpsuit Apparatus                       Don't You Fake It   
9                    blink-182                               blink-182   
10                      ayokay                 In the Shape of a Dream   
11                Xuitcasecity                                 Shadows   
12                      Halsey                              Without Me   

                      track                track_id  danceability  energy  \
0            Hero / Heroine  1AnesEZjtNHT7Nr2Y4BuNR         0.422   0.904   
1       Dirty Little Secret  5ZdzNVOmCSp5HFLk0EgvJS         0.469   0.955   
2              All over You  4b9jRNwMUvABxTD1amyfA6         0.554   0.941   
3          You Suck At Love  2khCn0FtcHpiOPRchJxjfs         0.517   0.961   
4    Sugar, We're Goin Down  2TfSHkHiFO4gRztVIkggkE         0.494   0.841   
5                Move Along  58HpsDKeYoLtNhXFQyQmz5         0.526   0.920   
6              Ocean Avenue  23oxJmDc1V9uLUSmN2LIvx         0.486   0.904   
7   Dear Maria, Count Me In  0J69x3mqm7U6tBPKsjpsWR         0.465   0.896   
8                 Face Down  4wzjNqjKAKDU82e8uMhzmr         0.545   0.932   
9                I Miss You  1AdYZ6X00nXmO613Y7GJOl         0.423   0.714   
10             Stay With Me  65Bynqyt59f3fojjs1Uo41         0.695   0.695   
11                  Shadows  4jj6aha7bFaOVK3al0h3NY         0.542   0.798   
12               Without Me  5p7ujcrUXASCNwRaWNHR1C         0.752   0.488   

    key  loudness  mode  speechiness  acousticness  instrumentalness  \
0     0    -4.531     1       0.1020      0.020000          0.000004   
1    10    -4.253     1       0.0432      0.000343          0.000001   
2    10    -3.159     0       0.0347      0.008480          0.000000   
3     2    -2.482     1       0.0494      0.002450          0.000000   
4     7    -4.784     1       0.0838      0.005790          0.000000   
5     3    -3.866     1       0.0472      0.000124          0.000000   
6     6    -3.751     0       0.0638      0.000034          0.000028   
7     2    -3.126     1       0.0795      0.007250          0.000000   
8     7    -2.189     0       0.0399      0.000665          0.000000   
9    11    -8.295     1       0.0450      0.001130          0.000006   
10    2    -6.612     1       0.0706      0.489000          0.000190   
11    2    -3.967     1       0.0544      0.189000          0.000000   
12    6    -7.050     1       0.0705      0.297000          0.000009   

    liveness  valence    tempo  duration_ms  time_signature  
0     0.6860    0.320  163.929       232240               4  
1     0.5480    0.462  143.853       193653               4  
2     0.1020    0.524  134.916       202432               4  
3     0.1730    0.741  155.976       191040               4  
4     0.1220    0.567  162.013       229093               4  
5     0.3710    0.615  109.860       238880               4  
6     0.0947    0.786  173.734       198267               4  
7     0.2060    0.569  181.014       182827               4  
8     0.1270    0.465   92.956       192000               4  
9     0.0855    0.593  110.017       227250               4  
10    0.1310    0.468  100.021       189787               4  
11    0.4950    0.262   75.023       210000               4  
12    0.0936    0.533  136.041       201661               4

In [116]:
list(ind[0])

[5796, 8358, 8207, 5129, 6158, 617, 1975, 9777, 8789, 6532]

In [117]:
recommendations = train_df.iloc[list(ind[0])][['artist','album','track']]
recommendations

artist  \
5796                         JP Cooper   
8358                      Milky Chance   
8207                   The Cranberries   
5129                     Alex & Sierra   
6158                            Aquilo   
617                       Jason Aldean   
1975                     Half Moon Run   
9777                      Taylor Swift   
8789                    The Night Game   
6532  Andrew McMahon in the Wilderness   

                                             album  \
5796                                Five More Days   
8358                              Blossom (Deluxe)   
8207  Stars: The Best Of The Cranberries 1992-2002   
5129                                 It's About Us   
6158                                   Silhouettes   
617                                    Night Train   
1975                               Sun Leads Me On   
9777                                    reputation   
8789                                The Night Game   
6532              Cecilia And The Satellite (Live)   

                                 track  
5796                    Five More Days  
8358                               Ego  
8207                  When You're Gone  
5129                       Back to You  
6158                     I Gave It All  
617                        Night Train  
1975               Hands In The Garden  
9777                          Delicate  
8789                      The Outfield  
6532  Cecilia And The Satellite - Live